apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: docker.io/evrachr/website_deployment:v3
        name: my-container
        imagePullPolicy: Always
        ports: 
        - containerPort: 4000
          protocol: TCP
          name: web-app-port
        readinessProbe:
          httpGet:
            path: /papers
            port: web-app-port 
            scheme: HTTP  
          initialDelaySeconds: 5
          periodSeconds: 5  
        livenessProbe:
          httpGet:
            path: /papers
            port: web-app-port 
            scheme: HTTP  
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
status: {}
