name: Docker image for CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: evrachr/website_deployment
  DOCKER_TAG: v3  
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Login to Docker Hub   
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD    

      - name: Build Docker image
        run: |
          ls ${GITHUB_WORKSPACE}/docker/src-python
          docker build -f ${GITHUB_WORKSPACE}/docker/Dockerfile.txt -t $DOCKER_IMAGE:$DOCKER_TAG .

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          run: |
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:latest
