name: Docker image for CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: evrachr/website_deployment
  DOCKER_TAG: v3      
  PORT: 4000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Login to Docker Hub   
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Build Docker image
        run: |
          cd ${GITHUB_WORKSPACE}/docker
          docker build -f ./Dockerfile.txt -t $DOCKER_IMAGE:$DOCKER_TAG .

      - name: Run Docker image
        run: |
          /usr/bin/bash -c "docker run -p $PORT:$PORT $DOCKER_IMAGE:$DOCKER_TAG" & sleep 5 & curl -X GET http://localhost:$PORT
          if [ $? -eq 0 ]; then
            echo "HTTP response successful, pushing image to Docker Hub"
          else
            echo "HTTP response failed, not pushing image to Docker Hub"
          fi 

      - name: Push to Docker Hub
        run: |
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:latest
